repos:
  - repo: local
    hooks:
    - id: lint
      name: lint
      language: system
      entry: make lint
      always_run: true
      pass_filenames: false
      stage: [commit]

  - repo: local
    hooks:
    - id: cc
      name: cc
      language: system
      entry: make cc
      always_run: true
      pass_filenames: false
      stage: [commit]

  - repo: https://github.com/jorisroovers/gitlint
    # It must match the gitlint's version that is inside pyproject.toml
    rev: v0.17.0
    hooks:
      - id: gitlint
