services:
  postgres_test:
    image: 'postgres:14'
    container_name: postgres-test
    env_file: '.env'
    environment:
      - POSTGRES_DB=postgres_testes
      - POSTGRES_USER=postgres_testes
      - POSTGRES_PASSWORD=senha
    ports:
      - "5431:5432"

  postgres:
    image: 'postgres:14'
    container_name: garcom
    env_file: '.env'
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=senha
    ports:
      - "5432:5432"