services:
  api:
    build: '.'
    volumes:
      - '.:/code'
    env_file: '.env'
    command: 'make run'
    ports:
      - '8000:8000'
    depends_on:
      - postgres

  postgres:
    image: 'postgres:14'
    env_file: '.env'
    volumes:
      - 'postgres_data:/var/lib/postgresql/data/'

volumes:
  postgres_data:
