version: '3.5'
services:

  postgres:
    image: 'postgres:14'
    container_name: postgres-api
    env_file: '.env'
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5432:5432"